proxy_cache_path /tmp/cache keys_zone=my_cache:10m max_size=10m inactive=60s;
# miejsce na cache, nazwa strefy, rozmiar strefy, maksymalny rozmiar cache, czas do usuniecia



server {
    listen 80;

    # jak nie zostanie podana konkretna sciezka
    # to uzyj pliki z katalogu html, to co kopiowalismy w dockerfile
    # jesli nie ma nic po / to uzjyj index.html
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # stats
    location = /api/stats {
        proxy_pass http://backend:3000/stats;
        proxy_cache my_cache;
        proxy_cache_valid 200 30s;
        add_header X-Cache-Status $upstream_cache_status;
    }

    # pass do backendu dla reszty api
    location /api/ {
        proxy_pass http://backend:3000/;
    }
}
